"use server";

import { createHmac, timingSafeEqual } from "crypto";
import { getServiceRoleSupabase } from "@/lib/supabase-server";

/**
 * Verify the HMAC proof generated by the page at render time.
 * Valid for 2 hours. Uses the same secret as generateAdminProof() in page.tsx.
 */
function verifyAdminProof(proof: string): boolean {
  const parts = (proof ?? "").split(".");
  if (parts.length !== 2) return false;
  const [tsStr, mac] = parts;
  const ts = parseInt(tsStr, 10);
  if (isNaN(ts)) return false;
  // 2-hour window
  if (Math.abs(Date.now() / 1000 - ts) > 7200) return false;

  const secret =
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.OSAI_ADMIN_EMAIL ?? "fallback";
  const expected = createHmac("sha256", secret)
    .update(`admin-invite:${ts}`)
    .digest("hex");

  try {
    return timingSafeEqual(Buffer.from(mac, "hex"), Buffer.from(expected, "hex"));
  } catch {
    return false;
  }
}

export type InviteResult =
  | { ok: true; email: string; note?: "existing_user" }
  | { ok: false; message: string };

export async function sendDemoInvite(
  email: string,
  adminProof: string
): Promise<InviteResult> {
  // Verify the server-generated proof instead of re-checking Supabase cookies.
  // The page already validated Supabase auth before rendering and generating this proof.
  if (!verifyAdminProof(adminProof)) {
    return { ok: false, message: "Not authorized." };
  }

  const normalizedEmail = email.trim().toLowerCase();
  if (!normalizedEmail || !normalizedEmail.includes("@")) {
    return { ok: false, message: "Valid email required." };
  }

  const appUrl =
    process.env.NEXT_PUBLIC_APP_URL ?? process.env.SITE_URL ?? "https://deploysure.com";
  const redirectTo = `${appUrl}/auth/callback?next=/demo/generate`;

  const admin = getServiceRoleSupabase();

  const { data: inviteData, error } = await admin.auth.admin.inviteUserByEmail(
    normalizedEmail,
    { data: { demo_access: true }, redirectTo }
  );

  if (error) {
    // User already has an account — grant demo access directly and inform the admin.
    try {
      const { data: existingRow } = await admin
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .schema("auth" as any)
        .from("users")
        .select("id, app_metadata")
        .eq("email", normalizedEmail)
        .maybeSingle<{ id: string; app_metadata: Record<string, unknown> | null }>();

      if (existingRow?.id) {
        await admin.auth.admin.updateUserById(existingRow.id, {
          app_metadata: { ...(existingRow.app_metadata ?? {}), demo_access: true },
        });
        return { ok: true, email: normalizedEmail, note: "existing_user" };
      }
    } catch {
      // Fall through to the original error if the lookup fails.
    }

    return { ok: false, message: error.message };
  }

  // New invited user — stamp app_metadata (tamper-proof; only writable via service role).
  if (inviteData.user?.id) {
    await admin.auth.admin.updateUserById(inviteData.user.id, {
      app_metadata: { demo_access: true },
    });
  }

  return { ok: true, email: normalizedEmail };
}
